const colors = {
  light: {
    text: "#0d1a26",
    tint: "#0f8a7b",
    background: "#f9fbfb",
    foreground: "#0d1a26",
    card: "#ffffff",
    cardForeground: "#0d1a26",
    primary: "#0f8a7b",
    primaryForeground: "#ffffff",
    secondary: "#e3ebeb",
    secondaryForeground: "#0d1a26",
    muted: "#e7efef",
    mutedForeground: "#52667a",
    accent: "#0f8a7b",
    accentForeground: "#ffffff",
    destructive: "#d92626",
    destructiveForeground: "#ffffff",
    border: "#d3dede",
    input: "#d3dede",
    success: "#16a34a",
    successBg: "#dcfce7",
    warning: "#b45309",
    warningBg: "#fef3c7",
  },
  dark: {
    text: "#f9fbfb",
    tint: "#14b8a4",
    background: "#0d1a26",
    foreground: "#f9fbfb",
    card: "#101f30",
    cardForeground: "#f9fbfb",
    primary: "#14b8a4",
    primaryForeground: "#ffffff",
    secondary: "#1a3347",
    secondaryForeground: "#f9fbfb",
    muted: "#122740",
    mutedForeground: "#8cb5b0",
    accent: "#14b8a4",
    accentForeground: "#ffffff",
    destructive: "#e64d4d",
    destructiveForeground: "#ffffff",
    border: "#1a3347",
    input: "#1a3347",
    success: "#4ade80",
    successBg: "#052e16",
    warning: "#fbbf24",
    warningBg: "#1c1408",
  },
  radius: 4,
};

export default colors;
